(function (global) {
  "use strict";
  const STORAGE_KEY="mathTimerProgress",DEV_KEY="mathTimerDevSettings",SAVE_VERSION=3,MAX_AWARD_RECORDS=200,MAX_PET_LEVEL=10;
  const SEASON_DEFINITIONS={hauntedHarvest:{id:"hauntedHarvest",label:"Autumn",startDate:"09-15",endDate:"11-15"},winterWonder:{id:"winterWonder",label:"Winter",startDate:"11-16",endDate:"02-28"},springBloom:{id:"springBloom",label:"Spring",startDate:"03-01",endDate:"05-31"},summerSplash:{id:"summerSplash",label:"Summer",startDate:"06-01",endDate:"09-14"}};
  const RARITIES={Common:{label:"Common",color:"#52705b",duplicateXp:15},Rare:{label:"Rare",color:"#286fd1",duplicateXp:25},Epic:{label:"Epic",color:"#7952b3",duplicateXp:40},Legendary:{label:"Legendary",color:"#a05a00",duplicateXp:65}};
  const PET_ABILITIES={coinFinder:{name:"Coin Finder",kind:"coinChance",values:{1:.03,5:.05,10:.07},describe:v=>`${Math.round(v*100)}% chance to find 1 bonus coin after practice.`},completionBonus:{name:"Helpful Find",kind:"completionCoins",values:{1:.08,5:.11,10:.14},describe:v=>`${Math.round(v*100)}% chance to find 2 bonus coins after practice.`},streakReward:{name:"Strong Finish",kind:"streakCoins",values:{1:.12,5:.16,10:.2},describe:v=>`${Math.round(v*100)}% chance for 2 bonus coins after 27+ correct.`},luckyHatch:{name:"Lucky Hatch",kind:"hatchLuck",values:{1:.005,5:.01,10:.015},describe:v=>`${(v*100).toFixed(1)}% boost to rare egg results.`},petXpBoost:{name:"Quick Learner",kind:"petXpMultiplier",values:{1:1.1,5:1.15,10:1.2},describe:v=>`Earns ${Math.round((v-1)*100)}% more Pet XP.`},eggProgressBonus:{name:"Egg Helper",kind:"eggProgressChance",values:{1:.04,5:.06,10:.08},describe:v=>`${Math.round(v*100)}% chance for 1 extra egg step after practice.`},collectionXp:{name:"Team Spirit",kind:"collectionXpChance",values:{1:.08,5:.12,10:.16},describe:v=>`${Math.round(v*100)}% chance to share 3 XP with another pet.`},luckyGift:{name:"Tiny Treasure",kind:"giftChance",values:{1:.025,5:.035,10:.05},describe:v=>`${(v*100).toFixed(1)}% chance to find a 3-coin gift after practice.`},practiceGift:{name:"Supply Drop",kind:"practiceGift",values:{1:.06,5:.09,10:.12},describe:v=>`${Math.round(v*100)}% chance to find 2 bonus coins after any completed practice.`},highScoreBonus:{name:"High Five",kind:"highScoreBonus",values:{1:.12,5:.17,10:.22},describe:v=>`${Math.round(v*100)}% chance to find 3 bonus coins after 25+ correct.`},xpBurst:{name:"XP Spark",kind:"xpBurst",values:{1:.08,5:.12,10:.16},describe:v=>`${Math.round(v*100)}% chance to earn 10 extra Pet XP.`},perfectBonus:{name:"Perfect Treasure",kind:"perfectBonus",values:{1:.18,5:.25,10:.32},describe:v=>`${Math.round(v*100)}% chance to find 5 bonus coins after a perfect score.`},duplicateBoost:{name:"Familiar Friend",kind:"duplicateXpMultiplier",values:{1:1.15,5:1.25,10:1.35},describe:v=>`Duplicate pets give ${Math.round((v-1)*100)}% more XP.`}};
  const P=(id,name,icon,rarity,ability,tagline)=>({id,name,icon,rarity,ability,tagline});
  const PETS=[
    P("mouse","Mouse","🐭","Common",null,"A tiny, cheerful study buddy."),P("bunny","Bunny","🐰","Common",null,"Always ready for more practice."),P("turtle","Turtle","🐢","Common",null,"Slow, steady, and proud."),P("fox","Fox","🦊","Rare","coinFinder","A clever collector."),P("raccoon","Raccoon","🦝","Rare","completionBonus","Curious and resourceful."),P("golden-gecko","Golden Gecko","🦎","Epic","petXpBoost","A bright little climber."),
    P("frog","Frog","🐸","Common",null,"A bright-eyed trail friend."),P("parrot","Parrot","🦜","Common",null,"Colorful, curious company."),P("hedgehog","Hedgehog","🦔","Common",null,"Small pet, big encouragement."),P("red-panda","Red Panda","🐼","Rare","streakReward","A focused forest friend."),P("otter","Otter","🦦","Rare","collectionXp","A playful team player."),P("axolotl","Axolotl","🫧","Epic","eggProgressBonus","A rare underwater pal."),P("crystal-owl","Crystal Owl","🦉","Legendary","luckyHatch","A watchful crystal guardian."),
    P("moon-moth","Moon Moth","🦋","Common",null,"A calm friend from the night sky."),P("salamander","Salamander","🦎","Common",null,"Warm-hearted and curious."),P("baby-griffin","Baby Griffin","🪽","Rare","coinFinder","A brave little sky explorer."),P("cloud-dragon","Cloud Dragon","☁️","Epic","completionBonus","A soft friend above the clouds."),P("star-wolf","Star Wolf","🐺","Epic","streakReward","A loyal cosmic companion."),P("cosmic-dragon","Cosmic Dragon","🐉","Legendary","luckyGift","A legendary traveler."),
    P("black-cat","Black Cat","🐈‍⬛","Common",null,"Quiet, clever, and cozy."),P("pumpkin-mouse","Pumpkin Mouse","🐭","Common",null,"A harvest-time helper."),P("ghost-puppy","Ghost Puppy","🐶","Rare","coinFinder","Friendly, floaty, and fun."),P("moon-bat","Moon Bat","🦇","Epic","eggProgressBonus","A night-sky navigator."),P("phantom-fox","Phantom Fox","🦊","Legendary","luckyGift","A legendary autumn visitor."),
    P("snow-bunny","Snow Bunny","🐇","Common",null,"A soft and snowy friend."),P("penguin","Penguin","🐧","Common",null,"A cool practice companion."),P("arctic-fox","Arctic Fox","🦊","Rare","collectionXp","A quick friend from the snow."),P("snowy-owl","Snowy Owl","🦉","Epic","petXpBoost","A wise winter watcher."),P("aurora-reindeer","Aurora Reindeer","🦌","Legendary","luckyHatch","A glowing winter legend."),
    P("ladybug","Ladybug","🐞","Common",null,"A tiny garden explorer."),P("duckling","Duckling","🐥","Common",null,"A sunny pond friend."),P("hummingbird","Hummingbird","🐦","Rare","coinFinder","Fast, bright, and curious."),P("flower-fawn","Flower Fawn","🦌","Epic","collectionXp","A gentle spring friend."),P("rainbow-unicorn","Rainbow Unicorn","🦄","Legendary","luckyHatch","A legendary garden visitor."),P("sand-crab","Sand Crab","🦀","Common",null,"A sideways beach buddy."),P("sea-turtle","Sea Turtle","🐢","Rare","eggProgressBonus","A calm ocean traveler."),P("sun-ray","Sun Ray","🐠","Epic","completionBonus","A bright friend from the reef."),P("tide-dragon","Tide Dragon","🐲","Legendary","luckyGift","A legendary guardian of the waves."),
    P("gear-mouse","Gear Mouse","🐭","Common",null,"A tiny workshop inventor."),P("circuit-pup","Circuit Pup","🐕","Rare","practiceGift","A loyal robot-side helper."),P("holo-owl","Holo Owl","🦉","Epic","xpBurst","A glowing digital guide."),P("mech-dragon","Mech Dragon","🐲","Legendary","perfectBonus","A legendary machine guardian."),
    P("lava-beetle","Lava Beetle","🪲","Common",null,"A sturdy volcanic explorer."),P("ember-fox","Ember Fox","🦊","Rare","highScoreBonus","A bright and daring friend."),P("magma-ram","Magma Ram","🐏","Epic","duplicateBoost","A powerful mountain companion."),P("phoenix","Phoenix","🔥","Legendary","practiceGift","A legendary friend that rises again."),
    P("hamster","Hamster","🐹","Common",null,"A cheerful snack-sized friend."),P("sugar-glider","Sugar Glider","🐿️","Rare","petXpBoost","A speedy candy-cloud traveler."),P("gummy-bear","Gummy Bear","🐻","Epic","eggProgressBonus","A colorful and bouncy companion."),P("candy-unicorn","Candy Unicorn","🦄","Legendary","perfectBonus","A legendary sweet-sky visitor."),
    P("pufferfish","Pufferfish","🐡","Common",null,"A round little reef friend."),P("dolphin","Dolphin","🐬","Rare","collectionXp","A playful ocean teammate."),P("octopus","Octopus","🐙","Epic","coinFinder","A clever deep-sea collector."),P("leviathan","Leviathan","🐋","Legendary","luckyHatch","A legendary creature of the deep.")
  ];
  const EGGS=[
    {id:"starter-egg",name:"Meadow Egg",style:"meadow",tier:"common",theme:"Friendly first pets",price:25,levelsRequired:3,chances:{Common:90,Rare:10},pools:{Common:["mouse","bunny","turtle"],Rare:["fox","raccoon"]}},
    {id:"pond-egg",name:"Pond Egg",style:"pond",tier:"common",theme:"Little pond and garden friends",price:28,levelsRequired:3,chances:{Common:88,Rare:12},pools:{Common:["frog","duckling","sand-crab"],Rare:["otter"]}},
    {id:"backyard-egg",name:"Backyard Egg",style:"backyard",tier:"common",theme:"Cozy neighborhood friends",price:30,levelsRequired:3,chances:{Common:90,Rare:10},pools:{Common:["hamster","ladybug","hedgehog"],Rare:["raccoon"]}},
    {id:"explorer-egg",name:"Explorer Egg",style:"explorer",theme:"Woodland and water friends",price:60,levelsRequired:4,chances:{Common:55,Rare:30,Epic:13,Legendary:2},pools:{Common:["frog","parrot","hedgehog"],Rare:["red-panda","otter"],Epic:["axolotl"],Legendary:["crystal-owl"]}},
    {id:"mystic-egg",name:"Starlight Egg",style:"starlight",theme:"Magical sky creatures",price:105,levelsRequired:6,chances:{Common:42,Rare:32,Epic:21,Legendary:5},pools:{Common:["moon-moth","salamander"],Rare:["baby-griffin"],Epic:["cloud-dragon","star-wolf"],Legendary:["cosmic-dragon"]}},
    {id:"haunted-harvest-egg",name:"Harvest Moon Egg",style:"harvest",theme:"Cozy autumn friends",price:75,levelsRequired:5,seasonId:"hauntedHarvest",chances:{Common:55,Rare:28,Epic:14,Legendary:3},pools:{Common:["black-cat","pumpkin-mouse"],Rare:["ghost-puppy"],Epic:["moon-bat"],Legendary:["phantom-fox"]}},
    {id:"winter-wonder-egg",name:"Frost Crystal Egg",style:"frost",theme:"Snowy winter companions",price:80,levelsRequired:5,seasonId:"winterWonder",chances:{Common:55,Rare:28,Epic:14,Legendary:3},pools:{Common:["snow-bunny","penguin"],Rare:["arctic-fox"],Epic:["snowy-owl"],Legendary:["aurora-reindeer"]}},
    {id:"spring-bloom-egg",name:"Bloom Egg",style:"bloom",theme:"Bright garden friends",price:80,levelsRequired:5,seasonId:"springBloom",chances:{Common:55,Rare:28,Epic:14,Legendary:3},pools:{Common:["ladybug","duckling"],Rare:["hummingbird"],Epic:["flower-fawn"],Legendary:["rainbow-unicorn"]}},
    {id:"summer-splash-egg",name:"Tidal Egg",style:"tidal",theme:"Sunny shore companions",price:85,levelsRequired:5,seasonId:"summerSplash",chances:{Common:55,Rare:29,Epic:13,Legendary:3},pools:{Common:["sand-crab"],Rare:["sea-turtle"],Epic:["sun-ray"],Legendary:["tide-dragon"]}},
    {id:"robot-egg",name:"Robot Egg",style:"robot",theme:"Clever machine companions",price:70,levelsRequired:4,chances:{Common:54,Rare:30,Epic:13,Legendary:3},pools:{Common:["gear-mouse"],Rare:["circuit-pup"],Epic:["holo-owl"],Legendary:["mech-dragon"]}},
    {id:"volcano-egg",name:"Volcano Egg",style:"volcano",theme:"Fiery mountain friends",price:90,levelsRequired:5,chances:{Common:50,Rare:31,Epic:15,Legendary:4},pools:{Common:["lava-beetle"],Rare:["ember-fox"],Epic:["magma-ram"],Legendary:["phoenix"]}},
    {id:"candy-egg",name:"Candy Cloud Egg",style:"candy",theme:"Sweet and colorful companions",price:75,levelsRequired:4,chances:{Common:54,Rare:30,Epic:13,Legendary:3},pools:{Common:["hamster"],Rare:["sugar-glider"],Epic:["gummy-bear"],Legendary:["candy-unicorn"]}},
    {id:"deep-sea-egg",name:"Deep Sea Egg",style:"deepsea",theme:"Mysterious ocean friends",price:95,levelsRequired:5,chances:{Common:48,Rare:32,Epic:16,Legendary:4},pools:{Common:["pufferfish"],Rare:["dolphin"],Epic:["octopus"],Legendary:["leviathan"]}}
  ];
  const SHOP_ITEMS=[
    {id:"classic",name:"Bright Classroom",description:"Clean blue, white, and gold.",type:"theme",price:0,asset:"classic"},{id:"party",name:"Confetti Pop",description:"Berry colors and a perfect-score confetti burst.",type:"theme",price:65,asset:"party",effect:"confetti"},{id:"ocean",name:"Ocean Quest",description:"Calm teal water and soft wave shapes.",type:"theme",price:75,asset:"ocean",effect:"bubbles"},{id:"space",name:"Galaxy Quest",description:"Deep space colors with tiny stars.",type:"theme",price:90,asset:"space",effect:"stars"},{id:"arcade",name:"Pixel Arcade",description:"Electric purple and mint with an arcade glow.",type:"theme",price:85,asset:"arcade",effect:"pixels"},{id:"jungle",name:"Jungle Trek",description:"Leafy greens and sunny explorer colors.",type:"theme",price:75,asset:"jungle",effect:"leaves"},{id:"candy",name:"Candy Clouds",description:"Soft sherbet colors with playful clouds.",type:"theme",price:80,asset:"candy",effect:"confetti"},{id:"halloween",name:"Harvest Night",description:"Cozy pumpkin colors and a dusky sky.",type:"theme",price:70,asset:"halloween",effect:"bats",seasonId:"hauntedHarvest"},{id:"winter",name:"Snow Day",description:"Icy blue with gentle celebration snow.",type:"theme",price:75,asset:"winter",effect:"snow",seasonId:"winterWonder"},{id:"spring",name:"Garden Party",description:"Fresh greens, blossoms, and sunshine.",type:"theme",price:75,asset:"spring",effect:"leaves",seasonId:"springBloom"},{id:"sunset",name:"Summer Sunset",description:"Warm coral skies and cool ocean blue.",type:"theme",price:75,asset:"sunset",effect:"bubbles",seasonId:"summerSplash"},
    {id:"starter",name:"Happy Helpers",description:"A friendly starter mix for perfect scores.",type:"celebration",price:0,asset:"starter",previewGif:"arthur_celebrate.gif",gifs:["arthur_celebrate.gif","elmo_celebrate.gif","bluey_celebrate.gif","pokemon_pikachu.gif"]},{id:"adventure",name:"Big Adventures",description:"Dinosaurs, dragons, racing, and action.",type:"celebration",price:40,asset:"adventure",previewGif:"dinosaur_dance.gif",gifs:["dinosaur_dance.gif","dinosaur_rex.gif","httyd_smile.gif","httyd_toothless.gif","cars_race.gif"]},{id:"builders",name:"Builders Club",description:"Blocky builders and creative heroes.",type:"celebration",price:50,asset:"builders",previewGif:"lego_dance.gif",gifs:["lego_dance.gif","lego_batman.gif","lego_shocked.gif","minecraft_steve.gif","minecraft_creeper.gif","roblox_dance1.gif"]},{id:"superheroes",name:"Super Cheers",description:"Fast, fearless perfect-score celebrations.",type:"celebration",price:60,asset:"superheroes",previewGif:"teentitans_robin.gif",gifs:["hulk_dance.gif","spiderman_dance.gif","teentitans_robin.gif","sonic_run.gif","starwars_grogu.gif"]},{id:"dance",name:"Dance Break",description:"A lively collection of happy dances.",type:"celebration",price:70,asset:"dance",previewGif:"trolls_poppy.gif",gifs:["trolls_poppy.gif","trolls_baby.gif","minions_dance.gif","mario_dance.gif","toystory_dance.gif","stitch_elvis.gif"]},{id:"winter_friends",name:"Winter Friends",description:"Snowy friends for perfect-score days.",type:"celebration",price:65,asset:"winter_friends",previewGif:"holiday/frosty_bday.gif",seasonId:"winterWonder",gifs:["holiday/frosty_bday.gif","holiday/frozen_olaf.gif","holiday/snoopy_snowman.gif","holiday/bluey_penguin.gif","holiday/pokemon_snow.gif","holiday/grogu_snow.gif"]}
  ];
  const STARTS=["Take a breath.","Stay focused.","Trust what you know.","Go one step at a time.","Keep a steady pace.","Think each problem through.","Start when you feel ready.","Use the strategies you know."],ENDS=["You've got this!","Let's see what you can do!","Do your best!","Now let's go!","Keep moving forward!","Take your time!","Stay confident!","You can do it!","Finish strong!","Make this round count!"];
  const GROUPS={addition:{offset:0,levels:["2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20"]},subtraction:{offset:19,levels:["2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19"]},multiplication:{offset:37,levels:["2","3","4","5","6","7","8","9","13"]},squareroot:{offset:46,levels:["1"]},multiplication2:{offset:47,levels:["10","11","12","14","15","half"]},division:{offset:53,levels:["2","3","4","5","6","7","8","9","10","11","12","13"]},division2:{offset:65,levels:["2","3","4","5","6","7","8","9","10","11","12","13"]}};
  function getPet(id){return PETS.find(x=>x.id===id)||null} function getEgg(id){return EGGS.find(x=>x.id===id)||null} function getItem(id){return SHOP_ITEMS.find(x=>x.id===id)||null} function getSeasonForPet(id){const egg=EGGS.find(e=>e.seasonId&&Object.values(e.pools).flat().includes(id));return egg?SEASON_DEFINITIONS[egg.seasonId]:null}
  function xpForNextLevel(level){return level>=MAX_PET_LEVEL?0:20+level*10}
  function defaultState(){return{version:SAVE_VERSION,coins:0,ownedThemes:["classic"],ownedCelebrations:["starter"],equippedTheme:"classic",equippedCelebration:"starter",bestScores:{},awardedSessions:[],ownedPets:[],equippedPet:null,activeEgg:null}}
  function normalizeOwnedPet(v){if(!v||!getPet(v.petId))return null;let level=Number.isInteger(v.level)?Math.max(1,Math.min(10,v.level)):1,xp=Math.max(0,Math.floor(Number(v.xp)||0));while(level<10&&xp>=xpForNextLevel(level)){xp-=xpForNextLevel(level);level++}if(level===10)xp=0;return{petId:v.petId,level,xp}}
  function normalizeState(v){const s=v&&typeof v==="object"?v:{},themes=Array.isArray(s.ownedThemes)?s.ownedThemes.filter(id=>getItem(id)?.type==="theme"):[],celebs=Array.isArray(s.ownedCelebrations)?s.ownedCelebrations.filter(id=>getItem(id)?.type==="celebration"):[];if(!themes.includes("classic"))themes.unshift("classic");if(!celebs.includes("starter"))celebs.unshift("starter");const seen=new Set(),owned=(Array.isArray(s.ownedPets)?s.ownedPets:[]).map(normalizeOwnedPet).filter(p=>p&&!seen.has(p.petId)&&seen.add(p.petId));const ae=s.activeEgg&&getEgg(s.activeEgg.eggId)?{eggId:s.activeEgg.eggId,progress:Math.max(0,Math.min(getEgg(s.activeEgg.eggId).levelsRequired,Math.floor(Number(s.activeEgg.progress)||0)))}:null;return{version:SAVE_VERSION,coins:Number.isSafeInteger(s.coins)&&s.coins>=0?s.coins:0,ownedThemes:[...new Set(themes)],ownedCelebrations:[...new Set(celebs)],equippedTheme:themes.includes(s.equippedTheme)?s.equippedTheme:"classic",equippedCelebration:celebs.includes(s.equippedCelebration)?s.equippedCelebration:"starter",bestScores:s.bestScores&&typeof s.bestScores==="object"?Object.fromEntries(Object.entries(s.bestScores).filter(([,n])=>Number.isInteger(n)&&n>=0&&n<=30)):{},awardedSessions:Array.isArray(s.awardedSessions)?s.awardedSessions.filter(x=>typeof x==="string").slice(-MAX_AWARD_RECORDS):[],ownedPets:owned,equippedPet:owned.some(p=>p.petId===s.equippedPet)?s.equippedPet:null,activeEgg:ae}}
  function loadState(){try{return normalizeState(JSON.parse(global.localStorage.getItem(STORAGE_KEY)))}catch(_){return defaultState()}} function saveState(s){const n=normalizeState(s);global.localStorage.setItem(STORAGE_KEY,JSON.stringify(n));return n}
  function getDevSettings(){try{return JSON.parse(global.sessionStorage?.getItem(DEV_KEY)||"{}")||{}}catch(_){return{}}} function setDevSettings(v){global.sessionStorage?.setItem(DEV_KEY,JSON.stringify(v||{}))} function isAdminEnabled(){return global.sessionStorage?.getItem("mathTimerAdmin")==="1"}
  function seasonIsActive(id,date=new Date()){const over=getDevSettings().season;if(over==="all")return true;if(over==="none")return false;if(over)return over===id;const s=SEASON_DEFINITIONS[id];if(!s)return false;const key=`${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;return s.startDate<=s.endDate?key>=s.startDate&&key<=s.endDate:key>=s.startDate||key<=s.endDate}
  function isAvailable(e,date=new Date()){return!e?.seasonId||seasonIsActive(e.seasonId,date)} function isOwned(s,i){return i.type==="theme"?s.ownedThemes.includes(i.id):s.ownedCelebrations.includes(i.id)}
  function rotationIndex(date=new Date()){const d=new Date(date);d.setHours(0,0,0,0);return Math.floor(d.getTime()/86400000)+(Number(getDevSettings().shopOffset)||0)} function rotate(list,count,date){if(list.length<=count)return list;const start=(((rotationIndex(date)*count)%list.length)+list.length)%list.length;return Array.from({length:count},(_,i)=>list[(start+i)%list.length])}
  function seededRandom(seed){let x=(seed|0)||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
  function weightedDaily(list,count,date,salt=0){const remaining=[...list],picked=[],rng=seededRandom(rotationIndex(date)*2654435761+salt);while(picked.length<count&&remaining.length){const weights=remaining.map(item=>item.seasonId?1.75:1),total=weights.reduce((a,b)=>a+b,0);let roll=rng()*total,index=0;for(;index<remaining.length-1;index++){roll-=weights[index];if(roll<0)break}picked.push(remaining.splice(index,1)[0])}return picked}
  function getVisibleShopItems(date=new Date()){const available=SHOP_ITEMS.filter(i=>i.price>0&&isAvailable(i,date)),themes=weightedDaily(available.filter(i=>i.type==="theme"),3,date,117),celebrations=weightedDaily(available.filter(i=>i.type==="celebration"),3,date,431);return[...themes,...celebrations]}
  function getVisibleEggs(date=new Date()){const common=rotate(EGGS.filter(e=>e.tier==="common"),1,date),premium=weightedDaily(EGGS.filter(e=>e.tier!=="common"&&isAvailable(e,date)),2,date,809);return[...common,...premium]}
  function purchase(id){const item=getItem(id),s=loadState();if(!item)return{ok:false,reason:"not-found",state:s};if(isOwned(s,item))return{ok:false,reason:"already-owned",state:s};if(!isAvailable(item))return{ok:false,reason:"unavailable",state:s};if(s.coins<item.price)return{ok:false,reason:"insufficient-coins",needed:item.price-s.coins,state:s};s.coins-=item.price;(item.type==="theme"?s.ownedThemes:s.ownedCelebrations).push(id);const state=saveState(s);updateCoinDisplays(state.coins);return{ok:true,item,state}}
  function purchaseEgg(id){const egg=getEgg(id),s=loadState();if(!egg)return{ok:false,reason:"not-found",state:s};if(s.activeEgg)return{ok:false,reason:"egg-active",state:s};if(!isAvailable(egg))return{ok:false,reason:"unavailable",state:s};if(s.coins<egg.price)return{ok:false,reason:"insufficient-coins",needed:egg.price-s.coins,state:s};s.coins-=egg.price;s.activeEgg={eggId:id,progress:0};const state=saveState(s);updateCoinDisplays(state.coins);renderPlayerWidgets(state);return{ok:true,egg,state}}
  function claimStarterPet(petId,eggId){const state=loadState(),egg=getEgg(eggId),pet=getPet(petId);if(state.ownedPets.length)return{ok:false,reason:"already-claimed",state};if(!egg||egg.tier!=="common"||!egg.pools.Common.includes(petId)||!pet)return{ok:false,reason:"invalid-pet",state};state.ownedPets.push({petId,level:1,xp:0});state.equippedPet=petId;const saved=saveState(state);renderPlayerWidgets(saved);return{ok:true,pet,state:saved}}
  function equip(id){const item=getItem(id),s=loadState();if(!item||!isOwned(s,item))return{ok:false,reason:item?"not-owned":"not-found",state:s};if(item.type==="theme")s.equippedTheme=id;else s.equippedCelebration=id;const state=saveState(s);if(item.type==="theme")applyTheme(id);return{ok:true,item,state}} function equipPet(id){const pet=getPet(id),s=loadState();if(!pet||!s.ownedPets.some(p=>p.petId===id))return{ok:false,reason:pet?"not-owned":"not-found",state:s};s.equippedPet=id;const state=saveState(s);renderPlayerWidgets(state);return{ok:true,pet,state}}
  function abilityValue(v,l){const ks=Object.keys(v).map(Number).sort((a,b)=>a-b),lo=[...ks].reverse().find(k=>k<=l)||ks[0],hi=ks.find(k=>k>=l)||ks.at(-1);return lo===hi?v[lo]:v[lo]+(v[hi]-v[lo])*(l-lo)/(hi-lo)} function getAbilityInfo(id,level=1){const pet=getPet(id),a=pet&&PET_ABILITIES[pet.ability];if(!a)return null;const scale={Common:1,Rare:1.12,Epic:1.28,Legendary:1.48}[pet.rarity]||1,base=abilityValue(a.values,Math.max(1,Math.min(10,level))),value=a.kind==="petXpMultiplier"||a.kind==="duplicateXpMultiplier"?1+(base-1)*scale:base*scale;return{name:a.name,kind:a.kind,value,rarityScale:scale,description:a.describe(value)}}
  function addPetXp(p,amount){const before=p.level;if(p.level>=10)return{gained:0,levelsGained:0};const gained=Math.max(0,Math.floor(amount));p.xp+=gained;while(p.level<10&&p.xp>=xpForNextLevel(p.level)){p.xp-=xpForNextLevel(p.level);p.level++}if(p.level===10)p.xp=0;return{gained,levelsGained:p.level-before}}
  function pickHatch(egg,luck,rng){let roll=Math.max(0,rng()*100-luck*100),sum=0,rarity=Object.keys(egg.chances)[0];for(const[r,c]of Object.entries(egg.chances)){sum+=c;if(roll<sum){rarity=r;break}}const pool=egg.pools[rarity];return getPet(pool[Math.floor(rng()*pool.length)])}
  function hatchActiveEgg(s,rng=Math.random){const egg=s.activeEgg&&getEgg(s.activeEgg.eggId);if(!egg)return null;const equipped=s.ownedPets.find(p=>p.petId===s.equippedPet),a=equipped&&getAbilityInfo(equipped.petId,equipped.level),pet=pickHatch(egg,a?.kind==="hatchLuck"?a.value:0,rng),owned=s.ownedPets.find(p=>p.petId===pet.id);let duplicateXp=0,levelsGained=0,autoEquipped=false;if(owned){duplicateXp=Math.round(RARITIES[pet.rarity].duplicateXp*(a?.kind==="duplicateXpMultiplier"?a.value:1));levelsGained=addPetXp(owned,duplicateXp).levelsGained}else{s.ownedPets.push({petId:pet.id,level:1,xp:0});if(!s.equippedPet){s.equippedPet=pet.id;autoEquipped=true}}s.activeEgg=null;return{eggId:egg.id,petId:pet.id,duplicate:!!owned,duplicateXp,levelsGained,autoEquipped}}
  function calculateCoins(n){n=Math.max(0,Math.min(30,Math.floor(Number(n)||0)));return n<10?0:n<15?2:n<20?4:n<25?6:n<28?8:n===28?10:n===29?12:16}
  function awardCompletion(sessionId,score,testId,random){if(!sessionId||typeof sessionId!=="string")return{ok:false,reason:"invalid-session",coinsAwarded:0,state:loadState()};const s=loadState();if(s.awardedSessions.includes(sessionId))return{ok:false,reason:"duplicate",coinsAwarded:0,state:s};const rng=typeof random==="function"?random:Math.random,n=Math.max(0,Math.min(30,Math.floor(Number(score)||0))),baseCoins=calculateCoins(n);let bonusCoins=0,eggBonus=false,sharedXp=null;const equipped=s.ownedPets.find(p=>p.petId===s.equippedPet),a=equipped&&getAbilityInfo(equipped.petId,equipped.level);if(a?.kind==="coinChance")for(let i=0;i<n;i++)if(rng()<a.value)bonusCoins++;if(a?.kind==="completionCoins"&&rng()<a.value)bonusCoins+=2;if(a?.kind==="streakCoins"&&n>=27&&rng()<a.value)bonusCoins+=2;if(a?.kind==="giftChance"&&rng()<a.value)bonusCoins+=3;if(a?.kind==="practiceGift"&&rng()<a.value)bonusCoins+=2;if(a?.kind==="highScoreBonus"&&n>=25&&rng()<a.value)bonusCoins+=3;if(a?.kind==="perfectBonus"&&n===30&&rng()<a.value)bonusCoins+=5;if(equipped){let earnedXp=Math.round(10*(a?.kind==="petXpMultiplier"?a.value:1));if(a?.kind==="xpBurst"&&rng()<a.value)earnedXp+=10;addPetXp(equipped,earnedXp)}if(a?.kind==="collectionXpChance"&&rng()<a.value){const friends=s.ownedPets.filter(p=>p.petId!==equipped.petId&&p.level<10);if(friends.length){const f=friends[Math.floor(rng()*friends.length)];addPetXp(f,3);sharedXp=f.petId}}let hatchResult=null,eggProgress=0;if(s.activeEgg&&n>=10){s.activeEgg.progress++;if(a?.kind==="eggProgressChance"&&rng()<a.value){s.activeEgg.progress++;eggBonus=true}const egg=getEgg(s.activeEgg.eggId);s.activeEgg.progress=Math.min(egg.levelsRequired,s.activeEgg.progress);eggProgress=s.activeEgg.progress;if(eggProgress>=egg.levelsRequired)hatchResult=hatchActiveEgg(s,rng)}const coinsAwarded=baseCoins+bonusCoins;s.coins+=coinsAwarded;if(testId)s.bestScores[testId]=Math.max(s.bestScores[testId]||0,n);s.awardedSessions.push(sessionId);s.awardedSessions=s.awardedSessions.slice(-MAX_AWARD_RECORDS);const state=saveState(s);updateCoinDisplays(state.coins);renderPlayerWidgets(state);return{ok:true,coinsAwarded,baseCoins,bonusCoins,eggProgress,eggBonus,hatchResult,sharedXp,state}}
  function updateCoinDisplays(n){if(!global.document)return;const v=typeof n==="number"?n:loadState().coins;global.document.querySelectorAll("[data-coin-balance]").forEach(e=>e.textContent=String(v))} function applyTheme(id){if(global.document)global.document.documentElement.dataset.theme=getItem(id)?.type==="theme"?id:"classic"}
  function eggArt(egg,extra=""){return`<span class="egg-art egg-${egg.style} ${extra}" aria-hidden="true"><i></i><b></b></span>`}
  function renderPlayerWidgets(state=loadState()){if(!global.document)return;global.document.querySelectorAll("[data-active-egg]").forEach(el=>{if(!state.activeEgg){el.hidden=true;el.innerHTML="";return}const egg=getEgg(state.activeEgg.eggId),left=egg.levelsRequired-state.activeEgg.progress,season=egg.seasonId?SEASON_DEFINITIONS[egg.seasonId]:null;el.hidden=false;el.innerHTML=`${eggArt(egg,"egg-widget-icon")}<span>${season?`<small class="active-season">${season.label} egg</small>`:""}<strong>${egg.name}</strong><span>${state.activeEgg.progress} / ${egg.levelsRequired} practice rounds</span><span class="mini-progress"><i style="width:${state.activeEgg.progress/egg.levelsRequired*100}%"></i></span><small>${left} more to hatch</small></span>`});global.document.querySelectorAll("[data-equipped-pet]").forEach(el=>{const o=state.ownedPets.find(p=>p.petId===state.equippedPet),pet=o&&getPet(o.petId);if(!pet){el.hidden=true;el.innerHTML="";return}el.hidden=false;el.innerHTML=`<span aria-hidden="true">${pet.icon}</span><span><strong>${pet.name}</strong><small>Level ${o.level}</small></span>`})}
  function getIntroLine(id){const[name,level]=String(id||"").split("_"),g=GROUPS[name],rank=g?g.levels.indexOf(level):-1,i=g&&rank>=0?g.offset+rank:0;return`${STARTS[i%STARTS.length]} ${ENDS[Math.floor(i/STARTS.length)%ENDS.length]}`} function getCelebrationGif(){const i=getItem(loadState().equippedCelebration)||getItem("starter");return i.gifs[Math.floor(Math.random()*i.gifs.length)]} function createSessionId(){return global.crypto?.randomUUID?global.crypto.randomUUID():`session-${Date.now()}-${Math.random().toString(36).slice(2)}`}
  function showThemeEffect(){if(!global.document||global.matchMedia?.("(prefers-reduced-motion: reduce)").matches)return;const theme=getItem(loadState().equippedTheme);if(!theme?.effect)return;const layer=global.document.createElement("div");layer.className=`completion-effect effect-${theme.effect}`;layer.ariaHidden="true";layer.innerHTML='<span class="effect-burst"></span>';const count=theme.effect==="confetti"?64:40;for(let i=0;i<count;i++){const p=global.document.createElement("i"),angle=Math.PI*2*i/count,d=150+i%5*42;p.style.cssText=`--x:${i*37%100}%;--y:${8+i*29%76}%;--delay:${i%12*75}ms;--drift:${(i%7-3)*24}px;--size:${12+i%5*3}px;--duration:${2800+i%6*260}ms;--dx:${Math.cos(angle)*d}px;--dy:${Math.sin(angle)*d}px`;layer.appendChild(p)}global.document.body.appendChild(layer);global.setTimeout(()=>layer.remove(),5200)}
  const api={SHOP_ITEMS,PETS,EGGS,RARITIES,PET_ABILITIES,SEASON_DEFINITIONS,STORAGE_KEY,DEV_KEY,SAVE_VERSION,MAX_PET_LEVEL,defaultState,normalizeState,loadState,saveState,calculateCoins,awardCompletion,purchase,purchaseEgg,claimStarterPet,equip,equipPet,isOwned,isAvailable,seasonIsActive,getVisibleShopItems,getVisibleEggs,rotationIndex,getItem,getPet,getEgg,getSeasonForPet,getAbilityInfo,xpForNextLevel,addPetXp,hatchActiveEgg,getIntroLine,getCelebrationGif,createSessionId,applyTheme,updateCoinDisplays,renderPlayerWidgets,showThemeEffect,eggArt,getDevSettings,setDevSettings,isAdminEnabled};global.MathTimer=api;applyTheme(loadState().equippedTheme);if(global.document){const ready=()=>{updateCoinDisplays();renderPlayerWidgets()};global.document.readyState==="loading"?global.document.addEventListener("DOMContentLoaded",ready):ready()}if(typeof module!=="undefined"&&module.exports)module.exports=api;
})(typeof window!=="undefined"?window:globalThis);
