"use strict";
const message=document.getElementById("collection-message"),dialog=document.getElementById("pet-dialog"),detail=document.getElementById("pet-detail");let messageTimer;
const seasonIcons={hauntedHarvest:"🍂",winterWonder:"❄",springBloom:"🌸",summerSplash:"☀"};
function seasonBadge(season){return season?`<span class="season-badge season-${season.id}"><span aria-hidden="true">${seasonIcons[season.id]||"★"}</span>${season.label}</span>`:""}
function rarityLabel(r){return`<span class="rarity-label rarity-${r.toLowerCase()}">${r}</span>`}
function themePreview(item){return`<div class="shop-preview preview-${item.asset}"><div class="theme-miniature" aria-hidden="true"><span class="miniature-header"></span><span class="miniature-card"><i></i><i></i><i></i></span><span class="palette-dots"><i></i><i></i><i></i><i></i></span></div></div>`}
function renderCosmetics(type,container,state){container.replaceChildren();const ids=type==="theme"?state.ownedThemes:state.ownedCelebrations;ids.forEach(id=>{const item=MathTimer.getItem(id),equipped=type==="theme"?state.equippedTheme===id:state.equippedCelebration===id,card=document.createElement("article");card.className=`owned-card ${equipped?"is-equipped":""} ${item.seasonId?"is-seasonal":""}`;const visual=type==="theme"?themePreview(item):`<div class="shop-preview celebration-preview"><img src="assets/gifs/${item.previewGif}" alt="${item.name} preview"><span>${item.gifs.length} possible celebrations</span></div>`;card.innerHTML=`${visual}<div class="owned-card-copy">${seasonBadge(item.seasonId?MathTimer.SEASON_DEFINITIONS[item.seasonId]:null)}<h3>${item.name}</h3><p>${item.description}</p><button data-cosmetic="${id}" ${equipped?"disabled":""}>${equipped?"Using":"Use this"}</button></div>`;container.appendChild(card)})}
function petCard(pet,owned,state){const card=document.createElement("button"),season=MathTimer.getSeasonForPet(pet.id);card.className=`pet-card ${owned?"is-owned":"is-locked"} ${state.equippedPet===pet.id?"is-equipped":""} ${season?"is-seasonal":""}`;card.dataset.pet=pet.id;card.disabled=!owned;card.innerHTML=owned?`${state.equippedPet===pet.id?'<span class="equipped-flag">With you</span>':""}${seasonBadge(season)}<span class="pet-icon" aria-hidden="true">${pet.icon}</span><strong>${pet.name}</strong>${rarityLabel(pet.rarity)}<span>Level ${owned.level}</span><span class="xp-bar"><i style="width:${owned.level===10?100:owned.xp/MathTimer.xpForNextLevel(owned.level)*100}%"></i></span><small>${owned.level===10?"Max level":`${owned.xp} / ${MathTimer.xpForNextLevel(owned.level)} XP`}</small>`:`${seasonBadge(season)}<span class="pet-icon mystery" aria-hidden="true">?</span><strong>Mystery pet</strong><span>Find it in an egg</span>`;return card}
function render(){const state=MathTimer.loadState();renderCosmetics("theme",document.getElementById("owned-themes"),state);renderCosmetics("celebration",document.getElementById("owned-celebrations"),state);const grid=document.getElementById("pet-grid"),lockedGrid=document.getElementById("locked-pet-grid"),ownedIds=new Set(state.ownedPets.map(p=>p.petId));grid.replaceChildren();lockedGrid.replaceChildren();MathTimer.PETS.forEach(p=>{const owned=state.ownedPets.find(o=>o.petId===p.id);(owned?grid:lockedGrid).appendChild(petCard(p,owned,state))});document.getElementById("pet-empty").hidden=state.ownedPets.length>0;document.getElementById("locked-count").textContent=String(MathTimer.PETS.length-ownedIds.size);document.querySelector(".locked-pets").hidden=ownedIds.size===MathTimer.PETS.length;MathTimer.renderPlayerWidgets(state)}
function openPet(id){const state=MathTimer.loadState(),pet=MathTimer.getPet(id),owned=state.ownedPets.find(p=>p.petId===id);if(!owned)return;const ability=MathTimer.getAbilityInfo(id,owned.level),season=MathTimer.getSeasonForPet(id);detail.innerHTML=`<span class="pet-detail-icon" aria-hidden="true">${pet.icon}</span>${seasonBadge(season)}<h2>${pet.name}</h2>${rarityLabel(pet.rarity)}<p><strong>Level ${owned.level}</strong> · ${owned.level===10?"Max level":`${owned.xp} / ${MathTimer.xpForNextLevel(owned.level)} XP`}</p><div class="detail-effect"><strong>${ability?ability.name:"Companion"}</strong><p>${ability?ability.description:pet.tagline}</p></div><button data-equip-pet="${id}" ${state.equippedPet===id?"disabled":""}>${state.equippedPet===id?"With you now":"Choose pet"}</button>`;dialog.showModal()}
function showMessage(text){clearTimeout(messageTimer);message.textContent=text;message.className="shop-message is-visible success";messageTimer=setTimeout(()=>message.classList.remove("is-visible"),2600)}
document.querySelector(".collection-tabs").addEventListener("click",e=>{const b=e.target.closest("[data-tab]");if(!b)return;document.querySelectorAll("[data-tab]").forEach(x=>x.setAttribute("aria-selected",String(x===b)));document.querySelectorAll("[data-panel]").forEach(x=>x.hidden=x.dataset.panel!==b.dataset.tab)});
document.querySelector(".collection-page").addEventListener("click",e=>{const cosmetic=e.target.closest("[data-cosmetic]"),pet=e.target.closest("[data-pet]");if(cosmetic){MathTimer.equip(cosmetic.dataset.cosmetic);showMessage("Your choice is now in use.");render()}if(pet)openPet(pet.dataset.pet)});dialog.addEventListener("click",e=>{if(e.target===dialog||e.target.closest(".dialog-close")){dialog.close();return}const b=e.target.closest("[data-equip-pet]");if(b){MathTimer.equipPet(b.dataset.equipPet);dialog.close();showMessage("Your pet is now with you.");render()}});render();
