"use strict";
const themeContainer=document.getElementById("theme-items"),celebrationContainer=document.getElementById("celebration-items"),eggContainer=document.getElementById("egg-items"),shopMessage=document.getElementById("shop-message"),eggDialog=document.getElementById("egg-dialog"),eggDetail=document.getElementById("egg-detail");let shopMessageTimer;
const seasonIcons={hauntedHarvest:"🍂",winterWonder:"❄",springBloom:"🌸",summerSplash:"☀"};
function seasonBadge(entry){if(!entry?.seasonId)return"";const season=MathTimer.SEASON_DEFINITIONS[entry.seasonId];return`<span class="season-badge season-${entry.seasonId}"><span aria-hidden="true">${seasonIcons[entry.seasonId]||"★"}</span>${season.label}</span>`}
function themePreview(item){return`<div class="theme-miniature" aria-label="${item.name} color preview"><span class="miniature-header"></span><span class="miniature-card"><i></i><i></i><i></i></span><span class="palette-dots"><i></i><i></i><i></i><i></i></span></div>`}
function itemCard(item,state){const owned=MathTimer.isOwned(state,item),article=document.createElement("article");article.className=`shop-item shop-item-${item.type} ${item.seasonId?"is-seasonal":""}`;article.dataset.itemId=item.id;const preview=item.type==="theme"?`<div class="shop-preview preview-${item.asset}">${themePreview(item)}</div>`:`<div class="shop-preview celebration-preview"><img src="assets/gifs/${item.previewGif}" alt="One ${item.name} preview" loading="lazy"><span>1 of ${item.gifs.length} surprises</span></div>`;article.innerHTML=`${preview}<div class="shop-item-content">${seasonBadge(item)}<h3>${item.name}</h3><p>${item.description}</p></div><div class="shop-item-footer"><span class="item-price"><span class="coin-icon" aria-hidden="true"></span>${item.price}</span>${owned?'<span class="purchased-mark" aria-label="Already collected">✓ Collected</span>':`<button class="shop-action" data-action="get-item" data-item-id="${item.id}">Get</button>`}</div>`;return article}
function eggCard(egg,state,index){const article=document.createElement("article"),active=state.activeEgg?.eggId===egg.id,starterGift=state.ownedPets.length===0&&index===0&&egg.tier==="common";article.className=`egg-card ${active?"is-active":""} ${egg.seasonId?"is-seasonal":""} ${starterGift?"has-starter-gift":""}`;article.dataset.eggId=egg.id;article.innerHTML=`<button class="egg-peek" data-action="egg-info" data-egg-id="${egg.id}" aria-label="See ${egg.name} details">${MathTimer.eggArt(egg)}<span class="egg-card-copy"><span class="egg-badge-slot">${seasonBadge(egg)}</span><h3>${egg.name}</h3><p>${egg.theme}</p><span class="peek-label">See pets & chances →</span></span></button><div class="egg-steps">${starterGift?'<strong class="starter-gift-note">Your first pet is free</strong>':`<span>${egg.levelsRequired} practice rounds to hatch</span>`}</div><div class="shop-item-footer"><span class="item-price">${starterGift?"Free":`<span class="coin-icon" aria-hidden="true"></span>${egg.price}`}</span><button class="shop-action" data-action="${starterGift?"choose-starter":"get-egg"}" data-egg-id="${egg.id}" ${!starterGift&&state.activeEgg?"disabled":""}>${starterGift?"Choose a pet":active?"Hatching":state.activeEgg?"Egg in progress":"Get egg"}</button></div>`;return article}
function eggPets(egg){return Object.entries(egg.pools).map(([rarity,ids])=>`<div class="rarity-pet-row"><strong class="rarity-${rarity.toLowerCase()}">${rarity}</strong><div>${ids.map(id=>{const pet=MathTimer.getPet(id);return`<span class="pet-pill"><i aria-hidden="true">${pet.icon}</i>${pet.name}</span>`}).join("")}</div></div>`).join("")}
function openEgg(id){const egg=MathTimer.getEgg(id),odds=Object.entries(egg.chances).map(([rarity,chance])=>`<li><span class="rarity-dot rarity-${rarity.toLowerCase()}"></span><strong>${rarity}</strong><span>${chance}%</span></li>`).join("");eggDetail.innerHTML=`${MathTimer.eggArt(egg,"egg-detail-art")}${seasonBadge(egg)}<p class="section-label">Egg details</p><h2>${egg.name}</h2><p>${egg.theme}</p><div class="egg-detail-grid"><div><h3>Hatch chances</h3><ul class="odds-list">${odds}</ul></div><div><h3>Pets inside</h3>${eggPets(egg)}</div></div><p class="fair-note">Every egg result is random. Getting a pet you already have gives that pet XP.</p>`;eggDialog.showModal()}
function openStarterChoice(eggId){const egg=MathTimer.getEgg(eggId),choices=egg.pools.Common.map(id=>MathTimer.getPet(id));eggDetail.innerHTML=`${MathTimer.eggArt(egg,"egg-detail-art")}<p class="section-label">A welcome gift</p><h2>Choose your first pet</h2><p>Pick one friend from today’s ${egg.name}. It will join your collection for free.</p><div class="starter-pet-choices">${choices.map(pet=>`<button data-claim-starter="${pet.id}" data-egg-id="${egg.id}"><span aria-hidden="true">${pet.icon}</span><strong>${pet.name}</strong></button>`).join("")}</div>`;eggDialog.showModal()}
function renderShop(){const state=MathTimer.loadState(),eggs=MathTimer.getVisibleEggs();themeContainer.replaceChildren();celebrationContainer.replaceChildren();eggContainer.replaceChildren();MathTimer.getVisibleShopItems().forEach(item=>(item.type==="theme"?themeContainer:celebrationContainer).appendChild(itemCard(item,state)));eggs.forEach((egg,index)=>eggContainer.appendChild(eggCard(egg,state,index)));MathTimer.updateCoinDisplays(state.coins);MathTimer.renderPlayerWidgets(state)}
function showMessage(text,kind=""){clearTimeout(shopMessageTimer);shopMessage.textContent=text;shopMessage.className=`shop-message is-visible ${kind}`;shopMessageTimer=setTimeout(()=>shopMessage.classList.remove("is-visible"),3500)}
document.querySelector(".shop-page").addEventListener("click",event=>{const button=event.target.closest("[data-action]");if(!button)return;if(button.dataset.action==="egg-info"){openEgg(button.dataset.eggId);return}if(button.dataset.action==="choose-starter"){openStarterChoice(button.dataset.eggId);return}if(button.dataset.action==="get-egg"){const egg=MathTimer.getEgg(button.dataset.eggId),result=MathTimer.purchaseEgg(egg.id);showMessage(result.ok?`${egg.name} is ready to hatch. Complete ${egg.levelsRequired} practice rounds!`:result.reason==="egg-active"?"Finish your current egg first.":result.reason==="insufficient-coins"?`You need ${result.needed} more coins.`:"That egg is not available.",result.ok?"success":"notice");renderShop();return}const item=MathTimer.getItem(button.dataset.itemId),result=MathTimer.purchase(item.id);showMessage(result.ok?`${item.name} was added to your Collection.`:result.reason==="insufficient-coins"?`You need ${result.needed} more coins.`:"That reward is not available.",result.ok?"success":"notice");renderShop()});
eggDialog.addEventListener("click",event=>{const claim=event.target.closest("[data-claim-starter]");if(claim){const result=MathTimer.claimStarterPet(claim.dataset.claimStarter,claim.dataset.eggId);eggDialog.close();showMessage(result.ok?`${result.pet.name} joined your collection!`:"Your starter pet was already claimed.",result.ok?"success":"notice");renderShop();return}if(event.target===eggDialog||event.target.closest(".dialog-close"))eggDialog.close()});
renderShop();
